Added some methods that were called but did not exist!
On line 36 `from_rgb` was called, despite there being no such function

caused error
```
in lib/stumpy_core/src/stumpy_core/rgba/from_rgba.cr:36: undefined method 'from_rgb' for StumpyCore::RGBA:Class (did you mean 'from_rgb8'?)

      self.from_rgb(r, g, b)
           ^~~~~~~~
```